language: python
env:
  - JAVAVER="oracle17"
  - JAVAVER="oracle18"
  - JAVAVER="openjdk17"
  - JAVAVER="openjdk18"
  - JAVAVER="openjdk17-devel"
  - JAVAVER="openjdk18-devel"
services:
  - docker
before_install:
  - sudo apt-get update
  - sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" docker-engine

script:
    - docker build --build-arg JAVAVER=$JAVAVER -t devslave-c7-test .
