sudo: required

language: java

services:
  - docker

env:
  - JAVAVER="oracle17"
  - JAVAVER="oracle18"
  - JAVAVER="openjdk17"
  - JAVAVER="openjdk18"
  - JAVAVER="openjdk17-devel"
  - JAVAVER="openjdk18-devel"

before_install:
  - sudo apt-get update
  - sudo DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confnew" install docker-engine
  - docker -v

install:
  - make BUILDARGS="--build-arg JAVAVER=$JAVAVER"

script:
  - docker run -d --name jenkins jenkins
  - docker inspect -f {{.State.Running}} jenkins
  - d=10; while ! docker logs jenkins 2>&1 | grep "Jenkins is fully up and running" ; do sleep 10; d=$[$d -1]; if [ $d -lt 0 ]; then exit 1; fi; done
  - JENKINS_ADDR=`docker inspect --format '{{ .NetworkSettings.IPAddress }}' jenkins`
  - JENKINS_PORT=50000
  - make start ENV="-e JENKINS_PORT_8080_TCP_ADDR=$JENKINS_ADDR -e JENKINS_PORT_8080_TCP_PORT=$JENKINS_PORT" VOLUMES="-v /sys/fs/cgroup:/sys/fs/cgroup:ro -v /run -v /home/travis/build/openmicroscopy/devslave-c7-docker/testperm:/home/omero/testperm"
  - docker inspect -f {{.State.Running}} devslave
  - SLAVE_ADDR=`docker inspect --format '{{ .NetworkSettings.IPAddress }}' devslave`
  - d=10; while ! docker logs jenkins 2>&1 | grep "from /${SLAVE_ADDR}" ; do sleep 10; d=$[$d -1]; if [ $d -lt 0 ]; then exit 1; fi; done
  - docker exec -it devslave /bin/bash -c "service jenkins status -l"
  - docker exec -it devslave /bin/bash -c "su - omero -c \"echo \"this is test\" > ~/testperm/file \""
  - docker logs jenkins
  - make stop
  - make rm
